/* Generated by wayland-scanner 1.23.1 */

/*
 * Copyright © 2015, 2016 Red Hat
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice (including the next
 * paragraph) shall be included in all copies or substantial portions of the
 * Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

#include <stdbool.h>
#include <stdlib.h>
#include <stdint.h>
#include "wayland-util.h"

#ifndef __has_attribute
# define __has_attribute(x) 0  /* Compatibility with non-clang compilers. */
#endif

#if (__has_attribute(visibility) || defined(__GNUC__) && __GNUC__ >= 4)
#define WL_PRIVATE __attribute__ ((visibility("hidden")))
#else
#define WL_PRIVATE
#endif

extern const struct wl_interface wl_seat_interface;
extern const struct wl_interface zwp_primary_selection_device_v1_interface;
extern const struct wl_interface zwp_primary_selection_offer_v1_interface;
extern const struct wl_interface zwp_primary_selection_source_v1_interface;

static const struct wl_interface *wp_primary_selection_unstable_v1_types[] = {
	NULL,
	NULL,
	&zwp_primary_selection_source_v1_interface,
	&zwp_primary_selection_device_v1_interface,
	&wl_seat_interface,
	&zwp_primary_selection_source_v1_interface,
	NULL,
	&zwp_primary_selection_offer_v1_interface,
	&zwp_primary_selection_offer_v1_interface,
};

static const struct wl_message zwp_primary_selection_device_manager_v1_requests[] = {
	{ "create_source", "n", wp_primary_selection_unstable_v1_types + 2 },
	{ "get_device", "no", wp_primary_selection_unstable_v1_types + 3 },
	{ "destroy", "", wp_primary_selection_unstable_v1_types + 0 },
};

WL_PRIVATE const struct wl_interface zwp_primary_selection_device_manager_v1_interface = {
	"zwp_primary_selection_device_manager_v1", 1,
	3, zwp_primary_selection_device_manager_v1_requests,
	0, NULL,
};

static const struct wl_message zwp_primary_selection_device_v1_requests[] = {
	{ "set_selection", "?ou", wp_primary_selection_unstable_v1_types + 5 },
	{ "destroy", "", wp_primary_selection_unstable_v1_types + 0 },
};

static const struct wl_message zwp_primary_selection_device_v1_events[] = {
	{ "data_offer", "n", wp_primary_selection_unstable_v1_types + 7 },
	{ "selection", "?o", wp_primary_selection_unstable_v1_types + 8 },
};

WL_PRIVATE const struct wl_interface zwp_primary_selection_device_v1_interface = {
	"zwp_primary_selection_device_v1", 1,
	2, zwp_primary_selection_device_v1_requests,
	2, zwp_primary_selection_device_v1_events,
};

static const struct wl_message zwp_primary_selection_offer_v1_requests[] = {
	{ "receive", "sh", wp_primary_selection_unstable_v1_types + 0 },
	{ "destroy", "", wp_primary_selection_unstable_v1_types + 0 },
};

static const struct wl_message zwp_primary_selection_offer_v1_events[] = {
	{ "offer", "s", wp_primary_selection_unstable_v1_types + 0 },
};

WL_PRIVATE const struct wl_interface zwp_primary_selection_offer_v1_interface = {
	"zwp_primary_selection_offer_v1", 1,
	2, zwp_primary_selection_offer_v1_requests,
	1, zwp_primary_selection_offer_v1_events,
};

static const struct wl_message zwp_primary_selection_source_v1_requests[] = {
	{ "offer", "s", wp_primary_selection_unstable_v1_types + 0 },
	{ "destroy", "", wp_primary_selection_unstable_v1_types + 0 },
};

static const struct wl_message zwp_primary_selection_source_v1_events[] = {
	{ "send", "sh", wp_primary_selection_unstable_v1_types + 0 },
	{ "cancelled", "", wp_primary_selection_unstable_v1_types + 0 },
};

WL_PRIVATE const struct wl_interface zwp_primary_selection_source_v1_interface = {
	"zwp_primary_selection_source_v1", 1,
	2, zwp_primary_selection_source_v1_requests,
	2, zwp_primary_selection_source_v1_events,
};

