env:
  CIRRUS_CLONE_DEPTH: 3
  FEATURES: huge

freebsd_task:
  only_if: $CIRRUS_TAG == ''
  timeout_in: 20m
  freebsd_instance:
    image: freebsd-12-3
    image: freebsd-13-1
  install_script:
    - pkg update -f
    - pkg install -y gettext
  build_script:
    - NPROC=$(getconf _NPROCESSORS_ONLN)
    - ./configure --with-features=${FEATURES}
    - make -j${NPROC}
  test_script:
    - src/vim --version
      # run tests as user "cirrus" instead of root
    - pw useradd cirrus -m
    - chown -R cirrus:cirrus .
    - sudo -u cirrus make test
