# lychee.toml — exclude two legacy domains
# (patterns are regular expressions)
exclude = [
  '^https?://www\.openvms\.compaq\.com/.*',
  '^https?://www\.openvms\.digital\.com/.*',
  "http://sys/file"
]
