#############################  Runtime  #############################

# Maximum number of concurrent link checks.
max_concurrency = 14

#############################  Requests  ############################

# Comma-separated list of accepted status codes for valid links.
# Supported values are:
#
# accept = ["200..=204", "429"]
# accept = "200..=204, 429"
# accept = ["200", "429"]
# accept = "200, 429"
accept = ["100..=103", "200..=299","400", "429"]

#############################  Exclusions  ##########################

# Exclude URLs and mail addresses from checking. The values are treated as regular expressions
exclude = [
  '^https?://sys/file$',
  '^file://.*',
  '^https?://(www\.)?badges\.debian\.net/.*$',
  '^https?://(www\.)?repology\.org/.*$',
  '^https?://scan\.coverity\.com/.*$',
  '^https?://(www\.)?img\.shields\.io/.*$',
  '^https?://(www\.)?fossies\.org/.*$',
  'https://www.fleiner.com/vim/download.html',
  'https://www.adobe.com',
  'https://github.com/you/foobar.git',
  'http://vim\.sourceforge\.net/scripts/script\.php\?script_id=40$',
  'https://is.gd/',
  'https://wiki.contextgarden.net/Vim',
  'https?://(www\.)?forum\.vmssoftware\.com/.*$',
]

# Exclude paths from getting checked. The values are treated as regular expressions
exclude_path = [
  "src/po",
  "src/testdir",
]
