# vi:ft=sshconfig
Include ~/.ssh/*.conf

Host github.com gist.github.com
	User git
	IdentitiesOnly yes

Host server
	Hostname 192.168.10.1
	User alice
	Port 22222
	ProxyCommand ssh -W %h:%p 172.24.0.1

Host *
        ConnectTimeout 0
