" Maintainer:  Drew Vogel <dvogel@sidejump.org>
" Last Change: 2021 Jun 19

" Similar in spirit to rgb.txt, this plugin establishes a human-friendly name
" for every color listed in the CSS standard:
"
" https://www.w3.org/TR/css-color-3/

if exists('g:css_colors_load') && g:css_colors_load == 1
	namecolor rgb=#000000 name=css_black
	namecolor rgb=#c0c0c0 name=css_silver
	namecolor rgb=#808080 name=css_gray
	namecolor rgb=#FFFFFF name=css_white
	namecolor rgb=#800000 name=css_maroon
	namecolor rgb=#FF0000 name=css_red
	namecolor rgb=#800080 name=css_purple
	namecolor rgb=#FF00FF name=css_fuchsia
	namecolor rgb=#008000 name=css_green
	namecolor rgb=#00FF00 name=css_lime
	namecolor rgb=#808000 name=css_olive
	namecolor rgb=#FFFF00 name=css_yellow
	namecolor rgb=#000080 name=css_navy
	namecolor rgb=#0000FF name=css_blue
	namecolor rgb=#008080 name=css_teal
	namecolor rgb=#00FFFF name=css_aqua

	namecolor rgb=#f0f8ff name=css_aliceblue
	namecolor rgb=#faebd7 name=css_antiquewhite
	namecolor rgb=#00ffff name=css_aqua
	namecolor rgb=#7fffd4 name=css_aquamarine
	namecolor rgb=#f0ffff name=css_azure
	namecolor rgb=#f5f5dc name=css_beige
	namecolor rgb=#ffe4c4 name=css_bisque
	namecolor rgb=#000000 name=css_black
	namecolor rgb=#ffebcd name=css_blanchedalmond
	namecolor rgb=#0000ff name=css_blue
	namecolor rgb=#8a2be2 name=css_blueviolet
	namecolor rgb=#a52a2a name=css_brown
	namecolor rgb=#deb887 name=css_burlywood
	namecolor rgb=#5f9ea0 name=css_cadetblue
	namecolor rgb=#7fff00 name=css_chartreuse
	namecolor rgb=#d2691e name=css_chocolate
	namecolor rgb=#ff7f50 name=css_coral
	namecolor rgb=#6495ed name=css_cornflowerblue
	namecolor rgb=#fff8dc name=css_cornsilk
	namecolor rgb=#dc143c name=css_crimson
	namecolor rgb=#00ffff name=css_cyan
	namecolor rgb=#00008b name=css_darkblue
	namecolor rgb=#008b8b name=css_darkcyan
	namecolor rgb=#b8860b name=css_darkgoldenrod
	namecolor rgb=#a9a9a9 name=css_darkgray
	namecolor rgb=#006400 name=css_darkgreen
	namecolor rgb=#a9a9a9 name=css_darkgrey
	namecolor rgb=#bdb76b name=css_darkkhaki
	namecolor rgb=#8b008b name=css_darkmagenta
	namecolor rgb=#556b2f name=css_darkolivegreen
	namecolor rgb=#ff8c00 name=css_darkorange
	namecolor rgb=#9932cc name=css_darkorchid
	namecolor rgb=#8b0000 name=css_darkred
	namecolor rgb=#e9967a name=css_darksalmon
	namecolor rgb=#8fbc8f name=css_darkseagreen
	namecolor rgb=#483d8b name=css_darkslateblue
	namecolor rgb=#2f4f4f name=css_darkslategray
	namecolor rgb=#2f4f4f name=css_darkslategrey
	namecolor rgb=#00ced1 name=css_darkturquoise
	namecolor rgb=#9400d3 name=css_darkviolet
	namecolor rgb=#ff1493 name=css_deeppink
	namecolor rgb=#00bfff name=css_deepskyblue
	namecolor rgb=#696969 name=css_dimgray
	namecolor rgb=#696969 name=css_dimgrey
	namecolor rgb=#1e90ff name=css_dodgerblue
	namecolor rgb=#b22222 name=css_firebrick
	namecolor rgb=#fffaf0 name=css_floralwhite
	namecolor rgb=#228b22 name=css_forestgreen
	namecolor rgb=#ff00ff name=css_fuchsia
	namecolor rgb=#dcdcdc name=css_gainsboro
	namecolor rgb=#f8f8ff name=css_ghostwhite
	namecolor rgb=#ffd700 name=css_gold
	namecolor rgb=#daa520 name=css_goldenrod
	namecolor rgb=#808080 name=css_gray
	namecolor rgb=#008000 name=css_green
	namecolor rgb=#adff2f name=css_greenyellow
	namecolor rgb=#808080 name=css_grey
	namecolor rgb=#f0fff0 name=css_honeydew
	namecolor rgb=#ff69b4 name=css_hotpink
	namecolor rgb=#cd5c5c name=css_indianred
	namecolor rgb=#4b0082 name=css_indigo
	namecolor rgb=#fffff0 name=css_ivory
	namecolor rgb=#f0e68c name=css_khaki
	namecolor rgb=#e6e6fa name=css_lavender
	namecolor rgb=#fff0f5 name=css_lavenderblush
	namecolor rgb=#7cfc00 name=css_lawngreen
	namecolor rgb=#fffacd name=css_lemonchiffon
	namecolor rgb=#add8e6 name=css_lightblue
	namecolor rgb=#f08080 name=css_lightcoral
	namecolor rgb=#e0ffff name=css_lightcyan
	namecolor rgb=#fafad2 name=css_lightgoldenrodyellow
	namecolor rgb=#d3d3d3 name=css_lightgray
	namecolor rgb=#90ee90 name=css_lightgreen
	namecolor rgb=#d3d3d3 name=css_lightgrey
	namecolor rgb=#ffb6c1 name=css_lightpink
	namecolor rgb=#ffa07a name=css_lightsalmon
	namecolor rgb=#20b2aa name=css_lightseagreen
	namecolor rgb=#87cefa name=css_lightskyblue
	namecolor rgb=#778899 name=css_lightslategray
	namecolor rgb=#778899 name=css_lightslategrey
	namecolor rgb=#b0c4de name=css_lightsteelblue
	namecolor rgb=#ffffe0 name=css_lightyellow
	namecolor rgb=#00ff00 name=css_lime
	namecolor rgb=#32cd32 name=css_limegreen
	namecolor rgb=#faf0e6 name=css_linen
	namecolor rgb=#ff00ff name=css_magenta
	namecolor rgb=#800000 name=css_maroon
	namecolor rgb=#66cdaa name=css_mediumaquamarine
	namecolor rgb=#0000cd name=css_mediumblue
	namecolor rgb=#ba55d3 name=css_mediumorchid
	namecolor rgb=#9370db name=css_mediumpurple
	namecolor rgb=#3cb371 name=css_mediumseagreen
	namecolor rgb=#7b68ee name=css_mediumslateblue
	namecolor rgb=#00fa9a name=css_mediumspringgreen
	namecolor rgb=#48d1cc name=css_mediumturquoise
	namecolor rgb=#c71585 name=css_mediumvioletred
	namecolor rgb=#191970 name=css_midnightblue
	namecolor rgb=#f5fffa name=css_mintcream
	namecolor rgb=#ffe4e1 name=css_mistyrose
	namecolor rgb=#ffe4b5 name=css_moccasin
	namecolor rgb=#ffdead name=css_navajowhite
	namecolor rgb=#000080 name=css_navy
	namecolor rgb=#fdf5e6 name=css_oldlace
	namecolor rgb=#808000 name=css_olive
	namecolor rgb=#6b8e23 name=css_olivedrab
	namecolor rgb=#ffa500 name=css_orange
	namecolor rgb=#ff4500 name=css_orangered
	namecolor rgb=#da70d6 name=css_orchid
	namecolor rgb=#eee8aa name=css_palegoldenrod
	namecolor rgb=#98fb98 name=css_palegreen
	namecolor rgb=#afeeee name=css_paleturquoise
	namecolor rgb=#db7093 name=css_palevioletred
	namecolor rgb=#ffefd5 name=css_papayawhip
	namecolor rgb=#ffdab9 name=css_peachpuff
	namecolor rgb=#cd853f name=css_peru
	namecolor rgb=#ffc0cb name=css_pink
	namecolor rgb=#dda0dd name=css_plum
	namecolor rgb=#b0e0e6 name=css_powderblue
	namecolor rgb=#800080 name=css_purple
	namecolor rgb=#ff0000 name=css_red
	namecolor rgb=#bc8f8f name=css_rosybrown
	namecolor rgb=#4169e1 name=css_royalblue
	namecolor rgb=#8b4513 name=css_saddlebrown
	namecolor rgb=#fa8072 name=css_salmon
	namecolor rgb=#f4a460 name=css_sandybrown
	namecolor rgb=#2e8b57 name=css_seagreen
	namecolor rgb=#fff5ee name=css_seashell
	namecolor rgb=#a0522d name=css_sienna
	namecolor rgb=#c0c0c0 name=css_silver
	namecolor rgb=#87ceeb name=css_skyblue
	namecolor rgb=#6a5acd name=css_slateblue
	namecolor rgb=#708090 name=css_slategray
	namecolor rgb=#708090 name=css_slategrey
	namecolor rgb=#fffafa name=css_snow
	namecolor rgb=#00ff7f name=css_springgreen
	namecolor rgb=#4682b4 name=css_steelblue
	namecolor rgb=#d2b48c name=css_tan
	namecolor rgb=#008080 name=css_teal
	namecolor rgb=#d8bfd8 name=css_thistle
	namecolor rgb=#ff6347 name=css_tomato
	namecolor rgb=#40e0d0 name=css_turquoise
	namecolor rgb=#ee82ee name=css_violet
	namecolor rgb=#f5deb3 name=css_wheat
	namecolor rgb=#ffffff name=css_white
	namecolor rgb=#f5f5f5 name=css_whitesmoke
	namecolor rgb=#ffff00 name=css_yellow
	namecolor rgb=#9acd32 name=css_yellowgreen
endif

"vim: sw=4
