.TH EVIM 1 "12 августа 2024"
.SH НАЗНАЧЕНИЕ
Программа evim \[em] это упрощённый Vim, которая производит запуск редактора Vim
в безрежимном варианте редактирования файлов.
.SH КРАТКИЙ ОБЗОР
.br
.B evim
[аргументы] [файл ...]
.br
.B eview
.SH ОПИСАНИЕ
По команде
.B evim
запускается редактор
.B Vim
и выполняется настройка ряда параметров таким образом, чтобы его работа была как
у простых безрежимных редакторов. В этом режиме редактор Vim напоминает
редактор Notepad из MS Windows.
Вариант редактора
.B eVim
всегда запускается с поддержкой графического интерфейса, чтобы была возможность
взаимодействия с программой через меню и панель инструментов.
.PP
Этот вариант редактора сделан для тех, кто по каким-то причинам не в состоянии 
работать с обычным редактором Vim. Редактирование файлов при этом происходит
гораздо менее эффективно, чем при использовании стандартного варианта редактора.
.PP
По команде
.B eview
выполняются почти те же самые действия, но файл будет открыт "только для чтения".
Использование этой команды полностью идентично команде evim \-R.
.PP
Подробнее о редакторе Vim, аргументах запуска и т. п. смотрите в справочнике
vim(1).
.PP
По команде
.B evim
будет установлен параметр 'insertmode', что обеспечивает ввод текста напрямую в
буфер.
.br
Кроме того, настраиваются клавиатурные команды, позволяющие выполнять
копирование и вставку текста, используя такие же комбинации клавиш,
как в MS Windows.
Клавиши CTRL+X используются для вырезания текста, CTRL+C для копирования
и CTRL+V для вставки.
Чтобы выполнить ту же команду, которая раньше была назначена на клавиши CTRL+V,
используйте клавиши CTRL+Q.
.SH АРГУМЕНТЫ КОМАНДНОЙ СТРОКИ
См. справочник vim(1).
.SH ФАЙЛЫ
.TP 15
/usr/local/share/vim/vim??/evim.vim
Сценарий, который загружается для инициализации eVim.
.br
Здесь
.I "vim??"
означает сокращённую запись номера версии, например, vim91 для версии редактора
.B Vim 9.1
.SH ДРУГИМИ СЛОВАМИ
Вариант eVim также известен как "Vim для чайников".
Для наилучшего эффекта рекомендуется во время использования повязать
на голове платок, предварительно завязав на каждом конце по узелку.
.SH СМОТРИТЕ ТАКЖЕ
vim(1)
.SH АВТОРЫ
Большая часть редактора
.B Vim
была создана Брамом Моленаром (Bram Moolenaar), которому помогало огромное 
количество людей. См. меню Справка пункт Соавторы.
