.TH VIMDIFF 1 "2021 June 13"
.SH 名称
vimdiff \- 使用 Vim 同时编辑二至八个版本的文件并显示差异
.SH 概述
.br
.B vimdiff
[选项] 文件1 文件2 [文件3 [文件4 [文件5 [文件6 [文件7 [文件8]]]]]]
.PP
.B gvimdiff
.SH 描述
.B Vimdiff
会启动
.B Vim
并同时打开二到八个文件。
每个文件各占一个窗口。
文件之间的差异会被高亮显示。
这可以很方便的检查变更以及在不同版本间同步修改。
.PP
关于 Vim 本身的详细信息，请参见 vim(1)。
.PP
若以
.B gvimdiff
方式启动，则会启用图形界面（如果可用）。
.PP
每个窗口都会开启 'diff' 选项，用以高亮显示差异。
.br
选项 'wrap' 和 'scrollbind' 也会被开启，确保文本显示效果良好。
.br
选项 'foldmethod' 被设为 "diff"，这样未发生变更的行段会被自动折叠起来。
同时 'foldcolumn' 设为 2，方便用户发现、展开和关闭折叠。
.SH 选项
默认使用纵向分割窗口来对齐行，效果等同于指定了 "\-O" 参数。
若要改为横向分割，可使用 "\-o" 参数。
.PP
其他选项请参见 vim(1)。
.SH 另见
vim(1)
.SH 作者
绝大多数
.B Vim
代码由 Bram Moolenaar 完成，并得到了众多人士的大力协助。
参见
.B Vim
中的 ":help credits"。
