.TH VIMTUTOR 1 "12 августа 2024"
.SH НАЗНАЧЕНИЕ
Программа vimtutor \[em] выполняет запуск учебника по редактору Vim.
.SH КРАТКИЙ ОБЗОР
.br
.B vimtutor [\-g] [язык]
.SH ОПИСАНИЕ
По команде
.B vimtutor
выполняется запуск редактора
.B Vim.
с загруженным файлом, содержащем текст учебника. Но перед этим происходит
создание копии файла учебника, чтобы в нём можно было выполнять практические
задания без опасения испортить исходный файл.
.PP
Практический курс, который будет открыт по команде
.B vimtutor
полезен для новичков, желающих научиться самым основным командам редактора
.B Vim.
.PP
Через необязательный аргумент командной строки \-g даётся указание на запуск
учебника в графическом интерфейсе редактора, если это, конечно, возможно.
При не возможности выполнить это, будет запущен консольный вариант редактора
.B Vim.
.PP
Необязательный аргумент [язык] задаётся как двухсимвольный код языка, например,
"ru" или "it".
Если аргумент [язык] не указан, то используется язык, заданный в действующих
в настоящий момент региональных настройках. Если учебника на этом языке не
существует, то, по умолчанию, используется учебник на английском языке.
.PP
При работе с учебником, редактор
.B Vim
всегда запускается в режиме совместимости с редактором Vi.
.SH ФАЙЛЫ
Здесь и далее
.I "vim??"
означает сокращённую запись номера версии, например, vim91 для версии редактора
.B Vim 9.1
.TP 15
/usr/local/share/vim/vim??/tutor/tutor[.язык]
Файлы с текстом учебника
.B Vimtutor.
.TP 15
/usr/local/share/vim/vim??/tutor/tutor.vim
Командный файл редактора
.B Vim,
который используется для создания рабочей копии текста учебника
.B Vimtutor.
.SH АВТОРЫ
Учебник
.B Vimtutor
был впервые написан для Vi Майклом К. Пирсом (Michael C. Pierce) и Робертом К.
Уэа (Robert K. Ware) из Colorado School of Mines по идее Чарльза Смита (Charles
Smith) из Colorado State University. E-mail: bware@mines.colorado.edu (теперь
недоступен).
.br
Впоследствии учебник был доработан для использования в редакторе
.B Vim
Брамом Моленаром (Bram Moolenaar).
Имена переводчиков учебника упоминаются в соответствующих файлах.
.SH СМОТРИТЕ ТАКЖЕ
vim(1)
