.TH VIMTUTOR 1 "04 ноября 2024"
.SH НАЗНАЧЕНИЕ
Программа vimtutor \[em] выполняет запуск учебника по редактору Vim
.SH КРАТКИЙ ОБЗОР
.br
.B vimtutor [\-l | \-\-language ISO639] [\-c | \-\-chapter НОМЕР] [\-g | \-\-gui] [ISO639]
.br
.B vimtutor [\-h | \-\-help]
.br
.B vimtutor [\-\-list]
.SH ОПИСАНИЕ
По команде
.B vimtutor
выполняется запуск редактора
.B Vim.
с загруженным файлом, содержащем текст учебника.
.PP
Практический курс, который будет открыт по команде
.B vimtutor
полезен для новичков, желающих научиться самым основным командам редактора
.B Vim.
.PP
Необязательный аргумент [ISO639] задаётся как двух- или трёхсимвольный код языка,
например, "ru" или "it", или "bar".
.PP
По команде
.B Vimtutor
будет открыта созданная копии файла учебника, чтобы в нём можно было выполнять
практические задания без опасения испортить исходный файл.
.PP
При работе с учебником, редактор
.B Vim
всегда запускается в режиме совместимости с редактором
.B Vi.
.SH АРГУМЕНТЫ КОМАНДНОЙ СТРОКИ
.TP
.BR \-l ", " \-\-language =\fIISO639\fR
Задаёт двух- или трёхсимволный код языка. Например, "ru", "es", "bar". По
умолчанию используется язык, заданный в действующих региональных настройках,
если такие настройки есть. В противном случае используется английский язык.
.TP
.BR \-c ", " \-\-chapter =\fIНОМЕР\fR
Задаёт номер главы учебника. Значением может быть 1 или 2. По умолчанию будет
открыта первая глава учебника.
.TP
.BR \-g ", " \-\-gui
Указывает на запуск учебника в графическом интерфейсе редактора, если это
возможно. В противном случае будет запущен консольный вариант редактора
.B Vim.
.TP
.BR \-h ", " \-\-help
Будет показана краткая информация об аргументах и параметрах командной строки.
.TP
.BR \-\-list
Будет показана информация о доступных главах и языках учебника.
.SH ПРИМЕРЫ
Чтобы открыть первую главу учебника на немецком языке, наберите команду
.PP
.nf
.RS
vimtutor de
.RE
.fi
.PP
Чтобы открыть вторую главу учебника на английском языке, наберите команду
.PP
.nf
.RS
vimtutor -c2
.RE
.fi
.PP
Пример с использованием полных форм аргументов командной строки для баварского
языка с открытием первой главы учебника в графическом интерфейсе редактора
.PP
.nf
.RS
vimtutor --language bar --chapter 1 --gui
.RE
.fi
.SH ФАЙЛЫ
.TP 15
/usr/local/share/vim/vim??/tutor/tutor1[.ISO639]
Файлы с текстом первой главы учебника
.B Vimtutor.
.TP 15
/usr/local/share/vim/vim??/tutor/tutor2[.ISO639]
Файлы с текстом второй главы учебника
.B Vimtutor.
.TP 15
/usr/local/share/vim/vim??/tutor/tutor.vim
Командный файл редактора
.B Vim,
который используется для создания рабочей копии файла учебника
.B Vimtutor.
.SH АВТОРЫ
Учебник
.B Vimtutor
был впервые написан для Vi Майклом К. Пирсом (Michael C. Pierce) и Робертом К.
Уэа (Robert K. Ware) из Colorado School of Mines по идее Чарльза Смита (Charles
Smith) из Colorado State University.
.B E-mail: bware@mines.colorado.edu
(теперь недоступен).
.PP
Впоследствии учебник был доработан для использования в редакторе
.B Vim
Брамом Моленаром (Bram Moolenaar).
.PP
Имена переводчиков указаны в соответствующих файлах с переводами учебника.
.SH СМОТРИТЕ ТАКЖЕ
vim(1)
