// File automatically generated by cproto. Do not edit by hand!
/* linematch.c */
size_t linematch_nbuffers(const mmfile_t **diff_blk, const int *diff_len, const size_t ndiffs, int **decisions, int iwhite);
// vim: set ft=c :
