name: GitHub CI

on:
  push:
    branches: ["**"]
  pull_request:

# Cancels all previous workflow runs for pull requests that have not completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name for
  # pull requests or the commit hash for any other events.
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:

  linux:
    name: Linux
    uses: ./.github/workflows/ci-linux.yml
    secrets: inherit

  linux-asan:
    name: Linux ASan
    uses: ./.github/workflows/ci-linux_asan.yml
    secrets: inherit

  macos:
    name: macOS
    uses: ./.github/workflows/ci-macos.yml
    secrets: inherit

  windows:
    name: Windows
    uses: ./.github/workflows/ci-windows.yml
    secrets: inherit
